name: HACS Validation

on:
  push:
  pull_request:

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run HACS Validation
        uses: hacs/action@main
        with:
          category: integration
